* Synthetic binary selection example; objective is 9 at a=b=1, c=0.
NAME KNAPSACK
OBJSENSE MAX
ROWS
 N PROFIT
 L CAPACITY
COLUMNS
 M0 'MARKER' 'INTORG'
 a PROFIT 5 CAPACITY 1
 b PROFIT 4 CAPACITY 1
 c PROFIT 3 CAPACITY 1
 M1 'MARKER' 'INTEND'
RHS
 RHS1 CAPACITY 2
ENDATA
