/*
 * Cross-language crypto round-trip.
 *
 * Does a signature produced by Node's `crypto` (what the auth service will use)
 * actually verify under Monocypher (what the desktop client will use)?
 *
 * This is the highest-risk assumption in the offline-authorization design. Both
 * sides implement "Ed25519", but the realistic failure modes are mundane and
 * fatal: a seed extracted from the wrong JWK field, a public key that is not the
 * raw 32 bytes, a payload canonicalised differently on each side. Any of them
 * produces a client that silently rejects every valid credential, and it would
 * only ever surface in front of a real user.
 *
 * Vectors are generated by tests/scripts/make_test_vectors.mjs, which uses the
 * same Node code path as services/auth/scripts/generate-signing-key.mjs. They
 * are committed so `ctest` needs no Node.
 */

#include "sovereign/ed25519_verify.hpp"

#include "mini_test.hpp"

#include <cstdio>
#include <string>
#include <vector>

using namespace sovereign;

namespace {

// Prefer the absolute path baked in by CMake (see tests/CMakeLists.txt), because
// ctest and a direct run use different working directories and a bare relative
// path silently resolves under one but not the other.
#ifdef SOVEREIGN_TEST_DATA_DIR
const char* kDataDir = SOVEREIGN_TEST_DATA_DIR;
#else
const char* kDataDir = "tests/data";
#endif

/** Read a whole file, trimming trailing newlines. Empty string if absent. */
std::string read_file_trimmed(const std::string& path) {
  FILE* f = std::fopen(path.c_str(), "rb");
  if (f == nullptr) return std::string();
  std::string out;
  char buf[4096];
  while (fgets(buf, sizeof(buf), f)) out += buf;
  std::fclose(f);
  while (!out.empty() && (out.back() == '\n' || out.back() == '\r')) out.pop_back();
  return out;
}

/** Load a vector file, failing the test loudly rather than passing vacuously. */
std::vector<uint8_t> load_vector(const char* name) {
  const std::string path = std::string(kDataDir) + "/" + name;
  const std::string hex = read_file_trimmed(path);
  if (hex.empty()) {
    std::cerr << "\n  MISSING TEST VECTOR: " << path
              << "\n  Run: node tests/scripts/make_test_vectors.mjs\n";
    ::sovereign_test::Registry::instance().failures++;
    return std::vector<uint8_t>();
  }
  try {
    return hex_to_bytes(hex);
  } catch (const std::exception& e) {
    std::cerr << "\n  MALFORMED TEST VECTOR " << path << ": " << e.what() << "\n";
    ::sovereign_test::Registry::instance().failures++;
    return std::vector<uint8_t>();
  }
}

/** A structurally valid 32-byte key that is NOT all zeroes. */
std::vector<uint8_t> zero_nonzero_key() {
  std::vector<uint8_t> key(32, 0);
  key[0] = 0x42;
  return key;
}

}  // namespace

TEST(Ed25519Verify, VectorsArePresent) {
  // A crypto test that cannot fail is worse than no test. Prove the vectors
  // exist and have the right shape before asserting anything about them.
  const auto pub = load_vector("ed25519_test_pub.hex");
  const auto msg = load_vector("ed25519_test_msg.hex");
  const auto sig = load_vector("ed25519_test_sig.hex");

  EXPECT_EQ(pub.size(), static_cast<std::size_t>(32));
  EXPECT_EQ(sig.size(), static_cast<std::size_t>(64));
  EXPECT_TRUE(msg.size() > 0);
}

TEST(Ed25519Verify, AcceptsSignatureFromNode) {
  const auto pub = load_vector("ed25519_test_pub.hex");
  const auto msg = load_vector("ed25519_test_msg.hex");
  const auto sig = load_vector("ed25519_test_sig.hex");
  if (pub.size() != 32 || sig.size() != 64 || msg.empty()) return;

  // The whole point: Node-signed, Monocypher-verified.
  EXPECT_TRUE(ed25519_verify(pub, msg, sig));
}

TEST(Ed25519Verify, RejectsFlippedSignatureBit) {
  const auto pub = load_vector("ed25519_test_pub.hex");
  const auto msg = load_vector("ed25519_test_msg.hex");
  auto sig = load_vector("ed25519_test_sig.hex");
  if (pub.size() != 32 || sig.size() != 64 || msg.empty()) return;

  // A verifier that does not actually verify will sail straight past this.
  sig[7] = static_cast<uint8_t>(sig[7] ^ 0x01);
  EXPECT_FALSE(ed25519_verify(pub, msg, sig));
}

TEST(Ed25519Verify, RejectsFlippedBitAtEverySignaturePosition) {
  const auto pub = load_vector("ed25519_test_pub.hex");
  const auto msg = load_vector("ed25519_test_msg.hex");
  const auto good = load_vector("ed25519_test_sig.hex");
  if (pub.size() != 32 || good.size() != 64 || msg.empty()) return;

  // Sweep every byte of the signature. A partial implementation (say, one that
  // only inspects the first half) would pass the single-bit test above and fail
  // here.
  int accepted = 0;
  for (std::size_t i = 0; i < good.size(); ++i) {
    auto sig = good;
    sig[i] = static_cast<uint8_t>(sig[i] ^ 0x80);
    if (ed25519_verify(pub, msg, sig)) ++accepted;
  }
  EXPECT_EQ(accepted, 0);
}

TEST(Ed25519Verify, RejectsTamperedMessage) {
  const auto pub = load_vector("ed25519_test_pub.hex");
  auto msg = load_vector("ed25519_test_msg.hex");
  const auto sig = load_vector("ed25519_test_sig.hex");
  if (pub.size() != 32 || sig.size() != 64 || msg.empty()) return;

  // This is the attack the offline model must resist: escalate a claim inside an
  // otherwise well-formed signed envelope (e.g. flip offline_access to true on a
  // credential that was never granted it).
  msg[0] = static_cast<uint8_t>(msg[0] ^ 0xff);
  EXPECT_FALSE(ed25519_verify(pub, msg, sig));
}

TEST(Ed25519Verify, RejectsAppendedMessageByte) {
  const auto pub = load_vector("ed25519_test_pub.hex");
  auto msg = load_vector("ed25519_test_msg.hex");
  const auto sig = load_vector("ed25519_test_sig.hex");
  if (pub.size() != 32 || sig.size() != 64 || msg.empty()) return;

  // Length-extension style attack: the signature must cover the exact bytes,
  // not a prefix.
  msg.push_back(0x00);
  EXPECT_FALSE(ed25519_verify(pub, msg, sig));
}

TEST(Ed25519Verify, RejectsWrongPublicKey) {
  auto pub = load_vector("ed25519_test_pub.hex");
  const auto msg = load_vector("ed25519_test_msg.hex");
  const auto sig = load_vector("ed25519_test_sig.hex");
  if (pub.size() != 32 || sig.size() != 64 || msg.empty()) return;

  // Forged by anyone who does not hold the server private key.
  pub[0] = static_cast<uint8_t>(pub[0] ^ 0xff);
  EXPECT_FALSE(ed25519_verify(pub, msg, sig));
}

TEST(Ed25519Verify, RejectsAllZeroKeyEvenThoughRawMonocypherAcceptsIt) {
  const auto msg = load_vector("ed25519_test_msg.hex");
  const auto sig = load_vector("ed25519_test_sig.hex");
  if (msg.empty() || sig.size() != 64) return;

  // Regression guard for a real weakness found by this very test suite.
  //
  // Ed25519 verification is malleable for small-order public keys. The identity
  // point (32 zero bytes) accepts a trivially forged 64-zero-byte signature, so
  // "signature verified" means nothing when the key is degenerate.
  //
  // Raw Monocypher's crypto_ed25519_check() does NOT reject this (libsodium's
  // crypto_sign_verify_detached does). Our wrapper must, so the offline
  // credential verifier can never be tricked into accepting anything.
  const std::vector<uint8_t> zero_key(32, 0);
  const std::vector<uint8_t> zero_sig(64, 0);

  EXPECT_FALSE(ed25519_verify(zero_key, msg, zero_sig));
  EXPECT_FALSE(ed25519_verify(zero_key, std::vector<uint8_t>{}, zero_sig));
  EXPECT_FALSE(ed25519_verify(zero_key, msg, sig));

  // Exactly one byte set must still be treated as a real (if wrong) key, so the
  // guard is not simply rejecting anything that looks unusual.
  std::vector<uint8_t> almost_zero(32, 0);
  almost_zero[31] = 0x01;
  EXPECT_FALSE(ed25519_verify(almost_zero, msg, sig));
}

TEST(Ed25519Verify, RejectsMalformedSizes) {
  const std::vector<uint8_t> msg{1, 2, 3};

  const std::vector<uint8_t> short_key(31, 0);
  const std::vector<uint8_t> long_key(33, 0);
  const std::vector<uint8_t> good_key(32, 0);
  const std::vector<uint8_t> good_sig(64, 0);
  const std::vector<uint8_t> short_sig(63, 0);
  const std::vector<uint8_t> long_sig(65, 0);

  EXPECT_FALSE(ed25519_verify(short_key, msg, good_sig));
  EXPECT_FALSE(ed25519_verify(long_key, msg, good_sig));
  EXPECT_FALSE(ed25519_verify(good_key, msg, short_sig));
  EXPECT_FALSE(ed25519_verify(good_key, msg, long_sig));

  // An empty message is a perfectly legal Ed25519 input. It must not be
  // rejected as "malformed" -- that would be a false negative on a valid
  // (if pointless) signature. The all-zero signature is still not valid, so the
  // result is false, but for the right reason: a bad signature, not a bad
  // message size.
  const std::vector<uint8_t> empty;
  EXPECT_FALSE(ed25519_verify(zero_nonzero_key(), empty, good_sig));
}

TEST(Ed25519Verify, HexHelperRejectsMalformedInput) {
  bool threw = false;
  try {
    hex_to_bytes("abc");  // odd length
  } catch (const std::invalid_argument&) {
    threw = true;
  }
  EXPECT_TRUE(threw);

  threw = false;
  try {
    hex_to_bytes("zz");  // not hex
  } catch (const std::invalid_argument&) {
    threw = true;
  }
  EXPECT_TRUE(threw);

  // Malformed hex must never reach the verifier as if it were a key.
  EXPECT_FALSE(ed25519_verify_hex("nothex", "payload", "alsonothex"));
}

TEST(Ed25519Verify, HexRoundTrips) {
  const std::vector<uint8_t> original{0x00, 0x01, 0x7f, 0x80, 0xfe, 0xff};
  const std::string hex = bytes_to_hex(original);
  EXPECT_EQ(hex, std::string("00017f80feff"));

  const auto back = hex_to_bytes(hex);
  EXPECT_EQ(back.size(), original.size());
  EXPECT_TRUE(back == original);
}

TEST(Ed25519Verify, Blake2bIsStableAndSensitive) {
  const std::vector<uint8_t> a{'s', 'o', 'v', 'e', 'r', 'e', 'i', 'g', 'n'};
  std::vector<uint8_t> b = a;
  b.push_back('n');

  const auto d1 = blake2b256(a);
  const auto d2 = blake2b256(a);
  const auto d3 = blake2b256(b);

  // 32 bytes: BLAKE2b-256, not the 64-byte default. Getting this wrong would
  // silently produce a different digest length than every caller expects.
  EXPECT_EQ(d1.size(), static_cast<std::size_t>(32));
  EXPECT_TRUE(d1 == d2);

  // One appended byte must change the digest.
  EXPECT_FALSE(d1 == d3);

  // Empty input must not crash.
  const std::vector<uint8_t> empty;
  EXPECT_EQ(blake2b256(empty).size(), static_cast<std::size_t>(32));
}
